-- AlterTable
ALTER TABLE "User" ADD COLUMN     "aboutMe" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "age" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "interests" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "occupation" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "sex" TEXT NOT NULL DEFAULT '';
